name: tutvideo
description: A new Flutter application.

version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3

  shared_preferences: ^2.2.2
  appwrite: ^12.0.0-rc.4
  google_fonts: ^6.2.1
  file_picker: ^6.2.0
  image_picker_web: ^3.1.1
  carousel_slider: ^4.2.1
  intl: ^0.19.0

  flutter_local_notifications: ^16.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
        - family: CustomIcons
          fonts:
            - asset: fonts/CustomIcons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700